# Generated by Django 4.2.3 on 2023-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_title_hobby_title_az_hobby_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Image'),
        ),
    ]
