# Generated by Django 4.2.3 on 2023-09-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_project_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(default='bxs:car-garage', help_text='Icons from https://icones.js.org/', max_length=64, verbose_name='Icon code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profession_az',
            field=models.CharField(help_text='Example: BackEnd, DevOps, WebDesign', max_length=155, verbose_name='[AZ]Profession'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profession_en',
            field=models.CharField(help_text='Example: BackEnd, DevOps, WebDesign', max_length=155, verbose_name='[EN]Profession'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profession_ru',
            field=models.CharField(help_text='Example: BackEnd, DevOps, WebDesign', max_length=155, verbose_name='[RU]Profession'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='icon',
            field=models.CharField(help_text='Example: ph:address-book \n Icons from https://icones.js.org/', max_length=64, verbose_name='Icon code'),
        ),
    ]
