# Generated by Django 4.2.3 on 2023-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_project_slug_sociallink_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='value',
        ),
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.CharField(help_text='Example: <code>2018-2020</code> or <code>2018 March-2018 August</code>', max_length=64, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profession_az',
            field=models.CharField(help_text='Example: <code>BackEnd, DevOps, WebDesign</code>', max_length=155, verbose_name='[AZ]Profession'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profession_en',
            field=models.CharField(help_text='Example: <code>BackEnd, DevOps, WebDesign</code>', max_length=155, verbose_name='[EN]Profession'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profession_ru',
            field=models.CharField(help_text='Example: <code>BackEnd, DevOps, WebDesign</code>', max_length=155, verbose_name='[RU]Profession'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='icon',
            field=models.CharField(help_text='Example: <code>ph:address-book</code> <br> Icons from <a href="https://icones.js.org/" target="_blank">here</a>', max_length=64, verbose_name='Icon code'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title_az',
            field=models.CharField(max_length=128, verbose_name='[AZ]Title'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title_en',
            field=models.CharField(max_length=128, verbose_name='[EN]Title'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title_ru',
            field=models.CharField(max_length=128, verbose_name='[RU]Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.CharField(help_text='Example: <code>Django, ReactJS, Redis</code>', max_length=128, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(help_text='Example: <code>ph:address-book</code> <br> Icons from <a href="https://icones.js.org/" target="_blank">here</a>', max_length=64, verbose_name='Icon code'),
        ),
        migrations.AlterField(
            model_name='whattodo',
            name='icon',
            field=models.CharField(help_text='Example: <code>ph:address-book</code> <br> Icons from <a href="https://icones.js.org/" target="_blank">here</a>', max_length=64, verbose_name='Icon code'),
        ),
    ]
