# Generated by Django 4.2.3 on 2023-09-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_hobby_value_alter_experience_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='icon',
            field=models.CharField(help_text='Example: <code>ph:address-book</code> <br> Icons from <a href="https://icones.js.org/" target="_blank">here</a>', max_length=255, verbose_name='Icon code'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(help_text='Example: <code>ph:address-book</code> <br> Icons from <a href="https://icones.js.org/" target="_blank">here</a>', max_length=255, verbose_name='Icon code'),
        ),
        migrations.AlterField(
            model_name='whattodo',
            name='icon',
            field=models.CharField(help_text='Example: <code>ph:address-book</code> <br> Icons from <a href="https://icones.js.org/" target="_blank">here</a>', max_length=255, verbose_name='Icon code'),
        ),
    ]
