# Generated by Django 4.2.3 on 2023-09-21 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_hobby_icon_alter_sociallink_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('meta_description', models.TextField(verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(verbose_name='Meta Keywords')),
            ],
            options={
                'verbose_name': 'SEO Info',
                'verbose_name_plural': 'SEO Info',
            },
        ),
    ]
