# Generated by Django 4.2.3 on 2023-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_experience_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
    ]
