# Generated by Django 4.2.3 on 2023-10-03 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('site_name', models.CharField(max_length=255, verbose_name='Site name')),
                ('telegram_notification', models.BooleanField(default=False, verbose_name='Telegram visit notification')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram bot token')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('region', models.CharField(max_length=255, verbose_name='Region')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('visits_count', models.PositiveIntegerField(default=1, verbose_name='Visit count')),
                ('last_visit_date', models.DateTimeField(default=datetime.datetime(2023, 10, 3, 13, 1, 28, 989258, tzinfo=datetime.timezone.utc), verbose_name='List visit date')),
                ('referrer', models.URLField(max_length=255, null=True, verbose_name='Referrer')),
                ('platform', models.CharField(max_length=255, verbose_name='Platform')),
                ('user_agent', models.CharField(max_length=255, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
        ),
        migrations.CreateModel(
            name='VisitFreeIP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ip', models.GenericIPAddressField(help_text='IP will not be processed as a visit', unique=True, verbose_name='IP')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_free', to='app_statistics.statisticsettings')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
